// src/modules/m2-inventario/services/inventario.mock.js
// Datos mock — reemplazar por llamadas al backend cuando esté disponible

export const CATEGORIAS = [
  { id: 'cat-1', nombre: 'Herramientas manuales' },
  { id: 'cat-2', nombre: 'Herramientas eléctricas' },
  { id: 'cat-3', nombre: 'Medición y nivel' },
  { id: 'cat-4', nombre: 'Corte y demolición' },
  { id: 'cat-5', nombre: 'Elevación y carga' },
]

export const ESTADOS = ['DISPONIBLE', 'EN_OBRA', 'EN_MANTENIMIENTO', 'RESERVADA', 'BAJA']

export const HERRAMIENTAS_MOCK = [
  {
    id: 'h-001',
    nombre: 'Taladro percutor Bosch GSB 21-2 RE',
    categoria: { id: 'cat-2', nombre: 'Herramientas eléctricas' },
    marca: 'Bosch',
    modelo: 'GSB 21-2 RE',
    numeroSerie: 'SN-2022-00341',
    descripcion: 'Incluye maletín, 3 brocas SDS y empuñadura lateral.',
    añoCompra: 2022,
    valor: 180000,
    estado: 'DISPONIBLE',
    codigoQR: 'FS-QR-0001',
  },
  {
    id: 'h-002',
    nombre: 'Nivel láser rotativo Leica Rugby 610',
    categoria: { id: 'cat-3', nombre: 'Medición y nivel' },
    marca: 'Leica',
    modelo: 'Rugby 610',
    numeroSerie: 'SN-2021-00112',
    descripcion: 'Con trípode y mira telescópica. Rango 200m.',
    añoCompra: 2021,
    valor: 950000,
    estado: 'EN_OBRA',
    codigoQR: 'FS-QR-0002',
  },
  {
    id: 'h-003',
    nombre: 'Amoladora angular Makita GA9020',
    categoria: { id: 'cat-4', nombre: 'Corte y demolición' },
    marca: 'Makita',
    modelo: 'GA9020',
    numeroSerie: 'SN-2020-00089',
    descripcion: 'Disco de 230mm. Requiere revisión de carbones.',
    añoCompra: 2020,
    valor: 95000,
    estado: 'EN_MANTENIMIENTO',
    codigoQR: 'FS-QR-0003',
  },
  {
    id: 'h-004',
    nombre: 'Martillo demoledor Hilti TE 500-AVR',
    categoria: { id: 'cat-4', nombre: 'Corte y demolición' },
    marca: 'Hilti',
    modelo: 'TE 500-AVR',
    numeroSerie: 'SN-2023-00201',
    descripcion: null,
    añoCompra: 2023,
    valor: 620000,
    estado: 'DISPONIBLE',
    codigoQR: 'FS-QR-0004',
  },
  {
    id: 'h-005',
    nombre: 'Cinta métrica Stanley FatMax 10m',
    categoria: { id: 'cat-3', nombre: 'Medición y nivel' },
    marca: 'Stanley',
    modelo: 'FatMax 10m',
    numeroSerie: null,
    descripcion: null,
    añoCompra: 2023,
    valor: 8500,
    estado: 'DISPONIBLE',
    codigoQR: 'FS-QR-0005',
  },
  {
    id: 'h-006',
    nombre: 'Sierra circular DeWalt DWE575',
    categoria: { id: 'cat-4', nombre: 'Corte y demolición' },
    marca: 'DeWalt',
    modelo: 'DWE575',
    numeroSerie: 'SN-2022-00456',
    descripcion: null,
    añoCompra: 2022,
    valor: 210000,
    estado: 'RESERVADA',
    codigoQR: 'FS-QR-0006',
  },
  {
    id: 'h-007',
    nombre: 'Tecle de cadena Yale 3 toneladas',
    categoria: { id: 'cat-5', nombre: 'Elevación y carga' },
    marca: 'Yale',
    modelo: 'CT-3000',
    numeroSerie: 'SN-2019-00033',
    descripcion: 'Cadena de 3m. Revisión anual al día.',
    añoCompra: 2019,
    valor: 145000,
    estado: 'DISPONIBLE',
    codigoQR: 'FS-QR-0007',
  },
  {
    id: 'h-008',
    nombre: 'Llave de impacto neumática Ingersoll Rand 2135',
    categoria: { id: 'cat-2', nombre: 'Herramientas eléctricas' },
    marca: 'Ingersoll Rand',
    modelo: '2135',
    numeroSerie: 'SN-2021-00278',
    descripcion: null,
    añoCompra: 2021,
    valor: 320000,
    estado: 'EN_OBRA',
    codigoQR: 'FS-QR-0008',
  },
  {
    id: 'h-009',
    nombre: 'Nivel de burbuja aluminio 120cm',
    categoria: { id: 'cat-3', nombre: 'Medición y nivel' },
    marca: 'Bahco',
    modelo: 'BL120',
    numeroSerie: null,
    descripcion: 'Burbuja dañada. Fuera de servicio.',
    añoCompra: 2018,
    valor: 12000,
    estado: 'BAJA',
    codigoQR: 'FS-QR-0009',
  },
  {
    id: 'h-010',
    nombre: 'Martillo de goma 800g',
    categoria: { id: 'cat-1', nombre: 'Herramientas manuales' },
    marca: 'Truper',
    modelo: 'MG-800',
    numeroSerie: null,
    descripcion: null,
    añoCompra: 2023,
    valor: 4200,
    estado: 'DISPONIBLE',
    codigoQR: 'FS-QR-0010',
  },
  {
    id: 'h-011',
    nombre: 'Destornillador inalámbrico Bosch GO 2',
    categoria: { id: 'cat-2', nombre: 'Herramientas eléctricas' },
    marca: 'Bosch',
    modelo: 'GO 2',
    numeroSerie: 'SN-2024-00011',
    descripcion: null,
    añoCompra: 2024,
    valor: 65000,
    estado: 'EN_OBRA',
    codigoQR: 'FS-QR-0011',
  },
  {
    id: 'h-012',
    nombre: 'Paleta de albañil acero 20cm',
    categoria: { id: 'cat-1', nombre: 'Herramientas manuales' },
    marca: 'Lay',
    modelo: 'PA-20',
    numeroSerie: null,
    descripcion: null,
    añoCompra: 2022,
    valor: 3500,
    estado: 'DISPONIBLE',
    codigoQR: 'FS-QR-0012',
  },
]

// Historial de movimientos mock por herramienta
export const MOVIMIENTOS_MOCK = {
  'h-001': [
    { id: 'm-1', tipo: 'EGRESO',   fecha: '2024-03-10', obra: 'Obra Belgrano',     responsable: 'Carlos Méndez',  observacion: null },
    { id: 'm-2', tipo: 'INGRESO',  fecha: '2024-03-18', obra: 'Obra Belgrano',     responsable: 'Carlos Méndez',  observacion: 'Devuelta en buen estado' },
    { id: 'm-3', tipo: 'EGRESO',   fecha: '2024-05-02', obra: 'Obra San Martín',   responsable: 'Laura Giménez',  observacion: null },
    { id: 'm-4', tipo: 'INGRESO',  fecha: '2024-05-15', obra: 'Obra San Martín',   responsable: 'Laura Giménez',  observacion: null },
  ],
  'h-002': [
    { id: 'm-5', tipo: 'EGRESO',   fecha: '2024-06-01', obra: 'Obra Palermo',      responsable: 'Roberto Sosa',   observacion: 'Se lleva también el trípode' },
  ],
  'h-003': [
    { id: 'm-6', tipo: 'EGRESO',        fecha: '2024-04-20', obra: 'Obra Caballito',    responsable: 'Diego Torres',   observacion: null },
    { id: 'm-7', tipo: 'INGRESO',       fecha: '2024-04-28', obra: 'Obra Caballito',    responsable: 'Diego Torres',   observacion: 'Disco gastado, necesita reemplazo' },
    { id: 'm-8', tipo: 'MANTENIMIENTO', fecha: '2024-05-05', obra: null,                responsable: 'Taller interno', observacion: 'Cambio de carbones y disco' },
  ],
  'h-004': [
    { id: 'm-9', tipo: 'EGRESO',   fecha: '2024-02-14', obra: 'Obra Recoleta',     responsable: 'Ana Vidal',      observacion: null },
    { id: 'm-10',tipo: 'INGRESO',  fecha: '2024-02-28', obra: 'Obra Recoleta',     responsable: 'Ana Vidal',      observacion: null },
  ],
}
